local M = {}

local function color(group, attr)
    local hl = vim.api.nvim_get_hl(0, { name = group, link = false })
    local val = hl[attr]
    return val and string.format("#%06x", val) or nil
end

-- Lines that belong to the color block we own
local function is_color_line(line)
    local patterns = {
        "^palette%s*=",
        "^background%s*=",
        "^foreground%s*=",
        "^selection%-background%s*=",
        "^selection%-foreground%s*=",
        "^cursor%-color%s*=",
        "^cursor%-text%s*=",
        "^theme%s*=",
        "^# Scheme:",
        "^# Generated by",
        "^# Neovim colorscheme:",
    }
    for _, pat in ipairs(patterns) do
        if line:match(pat) then return true end
    end
    return false
end

function M.sync()
    local ghostty_dir = vim.env.HOME .. "/Library/Application Support/com.mitchellh.ghostty"
    if vim.fn.isdirectory(ghostty_dir) == 0 then return end

    local bg = color("Normal", "bg") or "#000000"
    local fg = color("Normal", "fg") or "#ffffff"

    local color_block = {
        "# Neovim colorscheme: " .. (vim.g.colors_name or "unknown"),
        "background = " .. bg,
        "foreground = " .. fg,
        "cursor-color = "         .. (color("Cursor",          "bg") or fg),
        "selection-background = " .. (color("Visual",          "bg") or bg),
        "selection-foreground = " .. (color("Visual",          "fg") or fg),
        "palette = 0="  .. bg,
        "palette = 1="  .. (color("DiagnosticError", "fg") or fg),
        "palette = 2="  .. (color("String",          "fg") or fg),
        "palette = 3="  .. (color("DiagnosticWarn",  "fg") or fg),
        "palette = 4="  .. (color("Function",        "fg") or fg),
        "palette = 5="  .. (color("Keyword",         "fg") or fg),
        "palette = 6="  .. (color("DiagnosticInfo",  "fg") or fg),
        "palette = 7="  .. fg,
        "palette = 8="  .. (color("Comment",         "fg") or bg),
        "palette = 9="  .. (color("DiagnosticError", "fg") or fg),
        "palette = 10=" .. (color("String",          "fg") or fg),
        "palette = 11=" .. (color("DiagnosticWarn",  "fg") or fg),
        "palette = 12=" .. (color("Function",        "fg") or fg),
        "palette = 13=" .. (color("Special",         "fg") or fg),
        "palette = 14=" .. (color("DiagnosticHint",  "fg") or fg),
        "palette = 15=" .. fg,
    }

    local config_path = ghostty_dir .. "/config"
    local existing = vim.fn.filereadable(config_path) == 1
        and vim.fn.readfile(config_path)
        or {}

    -- Strip all previously-managed color lines
    local retained = vim.tbl_filter(function(line)
        return not is_color_line(line)
    end, existing)

    -- Trim trailing blank lines before appending
    while #retained > 0 and retained[#retained]:match("^%s*$") do
        table.remove(retained)
    end

    -- Append a blank separator then the new color block
    table.insert(retained, "")
    vim.list_extend(retained, color_block)

    vim.fn.writefile(retained, config_path)
end

return M
